# -*- coding: utf-8 -*-
"""Day23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vCHP1CxxZgRW6CsfnEQTBa_mOxl7wml4

Day 23
100 Days of Code
Rubenia Borge
"""

import pandas as pd
import numpy as np

#Hard-coded data for output represents the sales per 5 months for 3 types of cars 
companySales = {'Gender':['Children','Children','Children','Men','Men'], 
                'Class' : ['First','Second','Third','First','Second'], 
                'Survived': [117,152,171,167,129], 
                'Died':[382,318,703,516,506]}

#Creates a data frame with the correct order of columns 
df = pd.DataFrame(companySales,columns=["Gender","Class","Survived","BMW I3"])

#Prints out the table
print(df)